# Generated by Django 2.1.1 on 2018-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=12)),
                ('user_email', models.CharField(max_length=30)),
                ('about_item', models.CharField(max_length=200)),
                ('item_tag', models.CharField(max_length=20)),
                ('item_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='music',
        ),
    ]
