# Generated by Django 2.1.1 on 2018-09-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20180921_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
